### ISSUE TITLE
LTSA Scan for Noisy Data

### ISSUE THREAD

**Issue by Kourtney-Burger** [SAEL-SWFSC/adrift-analysis-methods#2]
@chomweaver @asimonis Do we want to list more steps here on how to record these time periods and are we using the logging feature in Triton? 

https://github.com/SAEL-SWFSC/adrift-analysis-methods/blob/848cfdc58d76d78c62f090ea4b65737aae7e792b/content/Data%20Archive/DataQualityCheck.qmd#L32-L35

**Comment by chomweaverNOAA** [comment]
Hi Kourtney, yes. We will want to use LTSA that have been created with 500Hz wav files. The parameters for the LTSA are 1S and 5Hz. And while logging we should be viewing the LTSA at a 2 hour window and scrolling through. I cannot remember if we wanted to log the type of noise or not or just log noise. Lets discuss more when Anne returns.

**Comment by asimonis** [comment]
My suggestion would be to use logger to define the start/end time of "bad data" and include type of noise in the comments (e.g. strumming, impulses, etc.)

**Comment by Kourtney-Burger** [comment]
Thank you both, I will update the methods with these details!
