### ISSUE TITLE
Uploading Deployment Details to Tethys

### ISSUE THREAD

**Issue by Kourtney-Burger** [SAEL-SWFSC/adrift-analysis-methods#4]
@asimonis Can we add more steps here for how to upload to Tethys, or can you walk me through how to do it and I will write them up? 
https://github.com/SAEL-SWFSC/adrift-analysis-methods/blob/848cfdc58d76d78c62f090ea4b65737aae7e792b/content/Data%20Archive/TethysDeployments.qmd#L11-L17

**Comment by Kourtney-Burger** [comment]
Also go over how to upload detection worksheets 
https://github.com/SAEL-SWFSC/adrift-analysis-methods/blob/848cfdc58d76d78c62f090ea4b65737aae7e792b/content/Data%20Archive/TethysDetections.qmd#L1-L13

**Comment by Kourtney-Burger** [comment]
What kind of metadata do we get from PAMpal that needs to go to Tethys? 

https://github.com/SAEL-SWFSC/adrift-analysis-methods/blob/b010b366f21f958cdaa53d26f550209526908ffb/content/Data%20Archive/TethysDeployments.qmd#L19-L21

**Comment by asimonis** [comment]
I don't currently incorporate any metadata from PAMpal into Tethys. 

The deployment and detection metadata are uploaded to Tethys using the dbSubmit function in Matlab. If you want to review how to do that, feel free to check my calendar and set up a 30-min meeting.
