### ISSUE TITLE
Decide how to reference data quality review 

### ISSUE THREAD

**Issue by asimonis** [SAEL-SWFSC/adrift-analysis-methods#9]
The data quality review is relevant for various workflows. For example, "bad data" should be removed from soundscape metrics. How can we cross-reference the data quality review here?

https://github.com/SAEL-SWFSC/adrift-analysis-methods/blob/dc4716e1877f8575458b6c7c575954b311bb51cc/content/Soundscapes/Metrics.qmd#L103C3-L103C3

**Comment by shannonrankin** [comment]
@chomweaver developed fantastic (and detailed) methods for assessing noise (and therefore identifying bad data). 

It should be linked to here (https://sael-swfsc.github.io/adrift-analysis-methods/content/DataArchive/DataQualityCheck.html#assess-data-quality), but this will need to be expanded.

Like with other methods, will be good to put simple methods here, with a link to the more detailed methods (all of which Cory has developed). 

I had to delay monitoring noise (Kourtney needs Matlab for now), when I pick it up, I can work on this, but will let Cory link the detailed documents.

**Comment by asimonis** [comment]
I added a link to this section in the soundscape metrics document, along with a brief description of what was done. Thank you!

**Comment by chomweaverNOAA** [comment]
Hi all I'm happy to expand upon this more when I have time or when I return from sea. My only caveat is that I did not do an extensive review of the data beyond the 250Hz range. The higher freq data may need to be explored more for noise.
